### ISSUE TITLE
Breaking change with aws provider on v4.0

### ISSUE THREAD

**Issue by lays147** [terraform-aws-modules/terraform-aws-lambda#268] opened 2022-02-14 12:57 UTC
## Description

Hi, last week the 4.0 version of the aws provider was released, and it broke `terraform plan` using this module because of changes in s3 api in this new version.

## Versions

 - Terraform:
1.1.4
 - Provider(s):
provider registry.terraform.io/hashicorp/aws v4.0.0

 - Module:
 This one

## Reproduction

1. Create a lambda function using this module
2. Run terraform plan

## Expected behavior

Deploy the module with success.

## Actual behavior

Terraform plan fails because of s3 errors.

### Terminal Output Screenshot(s)
```
╷
│ Warning: Argument is deprecated
│ 
│   with module.toil_tools_lambda_handler.aws_s3_bucket_object.lambda_package,
│   on .terraform/modules/toil_tools_lambda_handler/main.tf line 124, in resource "aws_s3_bucket_object" "lambda_package":
│  124:   bucket        = var.s3_bucket
│ 
│ Use the aws_s3_object resource instead
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with aws_s3_bucket.this,
│   on bucket.tf line 6, in resource "aws_s3_bucket" "this":
│    6: resource "aws_s3_bucket" "this" {
│ 
│ Can't configure a value for "server_side_encryption_configuration": its
│ value will be decided automatically based on the result of applying this
│ configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with aws_s3_bucket.this,
│   on bucket.tf line 6, in resource "aws_s3_bucket" "this":
│    6: resource "aws_s3_bucket" "this" {
│ 
│ Can't configure a value for "versioning": its value will be decided
│ automatically based on the result of applying this configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│ 
│   with aws_s3_bucket.this,
│   on bucket.tf line 10, in resource "aws_s3_bucket" "this":
│   10:   acl    = "private"
│ 
│ Can't configure a value for "acl": its value will be decided automatically
│ based on the result of applying this configuration.
╵
```

**Comment by antonbabenko** [comment] 2022-02-14 13:25
Thanks for opening this issue. One more thing to work on and think about :)

For the time being, please use AWS provider version 3.

**Comment by antonbabenko** [comment] 2022-02-14 14:02
I've just scheduled this for Friday - https://www.youtube.com/watch?v=CqRU41N6V68

**Comment by MooreDerek** [comment] 2022-02-24 23:39
@lays147 I don't the issue is with this module. There is no `bucket.tf` in the codebase. I think the issue is the upgrade to v4 of the provider has broken the codebase that this was raised on. The server side encryption and ACL are being set in the S3 Bucket Object here -> https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/main.tf#L125

**Comment by iainhtp** [comment] 2022-03-01 10:09
Interested in a version that works with terraform provider 4.2.0, since we require this for AWS Managed Grafana and we are trying to deploy a Grafana workspace with an associated Lambda function !

**Comment by guillaumelecerf** [comment] 2022-03-15 14:50
The deprecation warning is addressed in https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/280

**Comment by antonbabenko** [comment] 2022-03-28 08:23
Please use version 3.0.0 of this module to use AWS provider version 4.

Fixed by https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/296

**Closed by antonbabenko** 2022-03-28 08:23 UTC
