### ISSUE TITLE
Providing hash_extra for local_existing_package

### ISSUE THREAD

**Issue by andormarkus** [terraform-aws-modules/terraform-aws-lambda#124] opened 2021-03-08 11:41 UTC
Hi All,

In the current implementation `hash_extra` is only working when the package in created by this module.
We are compiling our packages in the CI/CD pipeline and the hash of the .zip file keeps changing however the source code does not change.

It would be great if `hash_extra`or similarly named variable would have effect on the `local_existing_package` as well.

Implementation could look like this:
`source_code_hash = (var.hash_extra != null ? var.hash_extra : local.filename == null ? false : fileexists(local.filename)) && !local.was_missing ? filebase64sha256(local.filename) : null`

Thanks,
Andor

**Comment by antonbabenko** [comment] 2021-03-08 13:08
Source code or timestamp is probably changing, too. If it would be the same, the produced zip archive should also be the same.

Could you please show the debug output as described [here](https://github.com/terraform-aws-modules/terraform-aws-lambda#-debug) with `DEBUG2` level?

**Comment by andormarkus** [comment] 2021-03-08 13:27
Hi Anton

Source code does not change because I just trigger a second run on CircleCI. Timestamp is manually overwritten `find . -exec touch -t 202001010000 {} \; `˜

![Screenshot 2021-03-08 at 14 15 03](https://user-images.githubusercontent.com/51825189/110326322-cf466680-8018-11eb-969e-345458488d8f.png)

Step 4282 and 4277 compiled the deployment package. 
![Screenshot 2021-03-08 at 14 17 03](https://user-images.githubusercontent.com/51825189/110326562-19c7e300-8019-11eb-8e87-2901e998630f.png)
![Screenshot 2021-03-08 at 14 18 22](https://user-images.githubusercontent.com/51825189/110326708-50056280-8019-11eb-8948-182b0b02f359.png)

As you can see the hash of the source code does not changes. However the has of the package is always changing. Im setting every time in the package as well.

![Screenshot 2021-03-08 at 14 20 43](https://user-images.githubusercontent.com/51825189/110326952-9d81cf80-8019-11eb-80c8-362feb22191d.png)

The problem is coming from when you make a `pip3 install --quiet --no-deps --target . --requirement requirements.txt` and the package is not pure python package. If the package contains C code like `wrapt` package pip will create a `.so`. This binary file will be always different and causing the shift of hash

This is how I generate packages
![Screenshot 2021-03-08 at 14 27 16](https://user-images.githubusercontent.com/51825189/110327560-6a8c0b80-801a-11eb-9459-ae45c528c11f.png)

**Comment by antonbabenko** [comment] 2021-03-08 13:44
Thanks a lot for the detailed reply, we will take a look at this when one of us has time.

**Comment by dpeliss** [comment] 2021-04-28 18:32
It would be great if we have some var to set the `source_code_hash`.

Currently, I have another tool that uploads the code to s3, so I don't use the upload from this module but the `s3_existing_package` parameter. In this case, I need to read the hash code from another file that the same tool populates, it's a gitops based deploy.

Without the option to explicitly set the `source_code_hash`, the code will never be updated, since the s3 keys don't change either.

The issue is quite the opposite that @andormarkus is facing but with the same solution.

**Comment by antonbabenko** [comment] 2021-04-28 18:38
@dpeliss You can set bucket, key, and version_id like in this commented block:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/6d2acf7ad8a28b1b9b48caab0570126de57d6051/examples/complete/main.tf#L142-L146

**Comment by dpeliss** [comment] 2021-04-28 19:24
I'll need to update my buckets to be versioned, but this will do the job, thank you @antonbabenko :call_me_hand:

**Comment by antonbabenko** [comment] 2021-08-30 11:58
Fixed in #175. Please update the module to use v2.10.0 or newer.

**Closed by antonbabenko** 2021-08-30 11:58 UTC
